// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/test-me/swagger-test/models"
)

// GetResourcesNameOKCode is the HTTP code returned for type GetResourcesNameOK
const GetResourcesNameOKCode int = 200

/*GetResourcesNameOK Service is returned

swagger:response getResourcesNameOK
*/
type GetResourcesNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewGetResourcesNameOK creates GetResourcesNameOK with default headers values
func NewGetResourcesNameOK() *GetResourcesNameOK {
	return &GetResourcesNameOK{}
}

// WithPayload adds the payload to the get resources name o k response
func (o *GetResourcesNameOK) WithPayload(payload *models.Resource) *GetResourcesNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resources name o k response
func (o *GetResourcesNameOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourcesNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
