// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetResourcesNameHandlerFunc turns a function with the right signature into a get resources name handler
type GetResourcesNameHandlerFunc func(GetResourcesNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetResourcesNameHandlerFunc) Handle(params GetResourcesNameParams) middleware.Responder {
	return fn(params)
}

// GetResourcesNameHandler interface for that can handle valid get resources name params
type GetResourcesNameHandler interface {
	Handle(GetResourcesNameParams) middleware.Responder
}

// NewGetResourcesName creates a new http.Handler for the get resources name operation
func NewGetResourcesName(ctx *middleware.Context, handler GetResourcesNameHandler) *GetResourcesName {
	return &GetResourcesName{Context: ctx, Handler: handler}
}

/*GetResourcesName swagger:route GET /resources/{name} getResourcesName

Read a single service

*/
type GetResourcesName struct {
	Context *middleware.Context
	Handler GetResourcesNameHandler
}

func (o *GetResourcesName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetResourcesNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
