// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetResourcesOKCode is the HTTP code returned for type GetResourcesOK
const GetResourcesOKCode int = 200

/*GetResourcesOK OK

swagger:response getResourcesOK
*/
type GetResourcesOK struct {
}

// NewGetResourcesOK creates GetResourcesOK with default headers values
func NewGetResourcesOK() *GetResourcesOK {
	return &GetResourcesOK{}
}

// WriteResponse to the client
func (o *GetResourcesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
