// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostResourcesOKCode is the HTTP code returned for type PostResourcesOK
const PostResourcesOKCode int = 200

/*PostResourcesOK OK

swagger:response postResourcesOK
*/
type PostResourcesOK struct {
}

// NewPostResourcesOK creates PostResourcesOK with default headers values
func NewPostResourcesOK() *PostResourcesOK {
	return &PostResourcesOK{}
}

// WriteResponse to the client
func (o *PostResourcesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostResourcesBadRequestCode is the HTTP code returned for type PostResourcesBadRequest
const PostResourcesBadRequestCode int = 400

/*PostResourcesBadRequest Invalid or incomplete resource

swagger:response postResourcesBadRequest
*/
type PostResourcesBadRequest struct {
}

// NewPostResourcesBadRequest creates PostResourcesBadRequest with default headers values
func NewPostResourcesBadRequest() *PostResourcesBadRequest {
	return &PostResourcesBadRequest{}
}

// WriteResponse to the client
func (o *PostResourcesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
