// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Service Catalog
REST API for Service Catalog


    Schemes:
      https
    Host: api.to-be-defined.com
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
