// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "REST API for Service Catalog",
    "title": "Service Catalog",
    "version": "1.0.0"
  },
  "host": "api.to-be-defined.com",
  "basePath": "/v1",
  "paths": {
    "/resources": {
      "get": {
        "summary": "Read all resources",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "summary": "Create new resource",
        "parameters": [
          {
            "name": "in",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Resource"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Invalid or incomplete resource"
          }
        }
      }
    },
    "/resources/{name}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Read a single service",
        "parameters": [
          {
            "type": "string",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Service is returned",
            "schema": {
              "$ref": "#/definitions/Resource"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Resource": {
      "type": "object",
      "properties": {
        "location": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
}
